spring:
  devtools:
    livereload:
      enabled: true
  datasource:
#    driver-class-name: org.postgresql.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(mTmeklnfXX2ISQFOt4XE/eYHM1SB/cTdOZJ98/jF/b9SbRpUhbpDm4aep3g8UbrVuVjVt19j5AchoFleIaAItg==)
    username: ENC(663QhnIKwurloIFkIjsD2A==)
    password: ENC(rNRfLF7icGDV18b4EJMI7kqZTL7l5L9u)
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8020
  tomcat:
    uri-encoding: UTF-8
  #URI Encoding
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800
mybatis:
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.leepay.payrollcalc.dto
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} [PayrollCalc] %clr(%logger - %M{10}){cyan} - %msg%n)"
  level:
    root: INFO
    com.leepay: DEBUG
    # logback과 겹치는 로그 제외용
    com.leepay.payrollcalc.mapper: OFF
    org:
      springframework:
        boot:
          autoconfigure: ERROR
        security: DEBUG
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: DEBUG
      sqlonly: DEBUG
      sqltiming: OFF
      connection: OFF
# 아래는 시스템에서 사용하는 프로퍼티 값임
system:
  login-mode: jwt # jwt / session로 구분
  lostark-api-key: ENC(TYR52ika/m6ACo6L5naiXcwZGElyox2MdHEj3oSpGhT1TyiSsgZxwxkx7YhBhQ8vLDq6g/ZAoZg9t4/YIZswxb4TNT+AXflB4kguX2rT1LIZP2FBRRTLEU2faUQzA4Ic4LmD+y+2IoCM8pJ1WgbFk7P/pGrD7MnzrSGaYdeARC9d4cC4438tyHHvSfIA0KExpsbBHPsU6Nc6qZuJOSq6VlGGs78wb4QUmEeXCk8p6IcCGU31UlDNwroGGvk13B/9lBSfrKPpUxcC5VdEwM0d/dN/9n321nGDhopFMyudPyMLhMurIKgmue5GIWc+RecPynBaB6LO/azy+qc3RfexTqRMYOlnaaj3biCDOOdNSlRI7qcG4oz2u8yAfU+AnOCDUGnhkXs4wXqZnBYMhOjdtpfJu5m3igtyae6Hinsk5apxSkVGJWHUBRbiUlNodFdZ53LqFUwub3PMvUJhIpagfx7A+ZAB6ESB6gvGSA5dstpndd2YzUlf/Q0prZbzUJo1ZNEBYr8L5Dv1mNDVrRpQe2ASNZMI5u99gvR59aXWVbciBZFSRxZPjh/dWFObQ0ik5ChPbyu4bjT7dQAkvyTg36gk9o+kKqZMsGOjU46IFeWoT+yBYiv/WlOu3M+jI7PcVbFaSzSlFmsqOPdzYk9fdZn7iEbIXnksv4XmcYj7yG+lsdalwv45L+mio5NuXmwXmIBdZtNFi3hCdeG4kkxhC1K9IR83MxOQOZlAB+MzBTx/PrREMRaXmeEeWmthKA8h5ltL0TXHRxMq1ZvJfXA/jvQDrxfCEFR4J6Dl+rv/Gpp0WEzi8S24daxV5JLKkqEC0WsSuro+BSUESbIbLsSNmZN/j6EDz1oQ)
  kakao-api-key:
    native: ENC(CU8DLxoOxdHCqw1tVQxItG6BKo0wJusCSk9J+22gq8/xBDK+4TgQrYI85IPie/Mw)
    restapi: ENC(xO2nXFfETatTPFE7iRPPiynKsPlRuDJpjPL5jQiRFFG5pOK631w30wMUBJRGsEaD)
    js: ENC(1CMsGzE06xrSs+/Ac8Ckj/hZBBsZDHJv4eKFVjak/Iaq5r7qfQMrJ64Gv3OGanhE)
    admin: ENC(Hj+/jbZ0rKIC9gWjm2ndccBMznOvFv35O0SI2L16rJWXpu0BLj7BtPxzYKSbm+HP)
  mail:
    mail-address: ENC(hN7afWLqVzP8a75Rg756w7kWVY8x6fGAfIyFSq3T504=)
    mail-password: ENC(a4NqSqBz68g+4g6BLDq+vOVkueLSSHF25D+4qDGU8wQ=)
  naver-api-key:
    clientId: ENC(ju7hAF5QSgLSZb3QbdxTDfXrc2ZD/MeB39Pl2yagEf8=)
    secretKey: ENC(Bses7BlBu9IKBt+TLyOYXDlTktxP49r5)