spring:
  devtools:
    livereload:
      enabled: true
  datasource:
#    driver-class-name: org.postgresql.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(NU9ppdpPWqoK77dCZe3Wes2dp01xqgIuMcMtanpaolrMTOOYt63XE9uFnb2A674rdRpLnd3nuwrcTBhhlCRKc8rRTyMI7xZR)
    username: ENC(663QhnIKwurloIFkIjsD2A==)
    password: ENC(rNRfLF7icGDV18b4EJMI7kqZTL7l5L9u)
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8020
  tomcat:
    uri-encoding: UTF-8
  #URI Encoding
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.leepay.payrollcalc.dto
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} [PayrollCalc] %clr(%logger - %M{10}){cyan} - %msg%n)"
  level:
    root: INFO
    com.leepay: DEBUG
    # logback과 겹치는 로그 제외용
    com.leepay.payrollcalc.mapper: OFF
    org:
      springframework:
        boot:
          autoconfigure: ERROR
        security: DEBUG
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: DEBUG
      sqlonly: DEBUG
      sqltiming: OFF
      connection: OFF
# 아래는 시스템에서 사용하는 프로퍼티 값임
system:
  login-mode: session # jwt / session로 구분
  kakao-api-key:
    native: ENC(EpJdaH2XbuYUe4l/+nGiwjf3e+rD16SiY4RmiZZ3mLoEZv0kvo4WRnZunGJa3qnK)
    restapi: ENC(Z7dZQsxGpq+EAavJoBANNE5W+yKfufB+cw3AYsdAy0QGzqVLHvf0t6tO5qkUCGAj)
    js: ENC(WxZ17tNwhUjuFkWF/AucErJ01PJpR08wWLs4WxyJvVukSPOe/ZUil328mZ5EMcz/)
    admin: ENC(GZLsi9GxuXMoyfuBrhDuCJLbdDahX1eDaMqA+aeKlq8EZnGUHOsUqkxQaSl/Smti)
  mail:
    mail-address: ENC(hN7afWLqVzP8a75Rg756w7kWVY8x6fGAfIyFSq3T504=)
    mail-password: ENC(a4NqSqBz68g+4g6BLDq+vOVkueLSSHF25D+4qDGU8wQ=)